
name: Homework_26

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1
    - name: docker build
      run: docker build -t ivanim/cw_4_1:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      
  push:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
    - name: docker login
      run:  echo ${{ secrets.DOCKER_TOKEN}}
    - name: docker push
      run: docker push ivanim/cw_4_1:$GITHUB_REF_NAME-$GITHUB_RUN_ID
      
  deploy:
    runs-on: ubuntu-latest
    needs: [push]
    
    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1
    - name: copy file docker-compose-server.yaml to server
      uses: app/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "docker-compose-server.yaml"
        target: "flask_app_docker/docker-compose.yaml"
    - name: deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        scripts:  |
          cd flask_app_docker
          echo ${{ secrets.PASSWORD }} | sudo -S docker-compose up -d
          
