
name: Homework_26

on: [push]

jobs:
  build_push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone my repo
      uses: actions/checkout@v2
      
    - name: docker login
      run:  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
  
    - name: docker build
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cw_4_1:version-1 .  
    
    - name: docker push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cw_4_1:version-1
      
  deploy:
    runs-on: ubuntu-latest
    needs: [build_push]
    
    steps:
    - name: Git clone my repo
      uses: actions/checkout@v2
    - name: create deploy/docker-compose.yaml
      run: |
          mkdir deploy
          cat docker-compose-server.yaml | envsubst > deploy/docker-compose.yaml
          
    - name: copy file docker-compose.yaml to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "deploy/docker-compose.yaml"
        target: "flask_app_docker"
        strip_components: 1
        
    - name: deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        scripts:  |
          cd flask_app_docker
          echo ${{ secrets.PASSWORD }} | sudo -S docker-compose up -d
          
